version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Users
    ports:
      - "5432:5432"
  
  redis:
    ports:
      - "6379:6379"
    restart: always
    image: redis

  app: 
    build: C:\Users\Karo\Desktop\Bot\Bot
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:1234@db/Users
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"